<?php
$z[0]=Array("global","\r\n                    \$a=\"\r\n                    <li class='col-3-1 last not-animated' data-animate='fadeInUp' >\";\r\n                      \$b=\"\r\n                    \r\n                    <li class='col-3-1 not-animated' data-animate='fadeInUp'>\";\r\n                      if ((@me%3)==0 && @me!=12)  @me=\$a;\r\n                      else  @me=\$b;\r\n                      ",0,421);
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("arcurl","",533,548);
$z[2]=Array("picname","",576,592);
$z[3]=Array("title","",599,613);
$z[4]=Array("arcurl","",723,738);
$z[5]=Array("title","",756,770);

?>