<?php
$z[0]=Array("global","\r\n                    \$a=\"\r\n                    <li class='col-3-1 last not-animated' data-animate='fadeInUp' >\";\r\n                      \$b=\"\r\n                    \r\n                    <li class='col-3-1 not-animated' data-animate='fadeInUp'>\";\r\n                      if ((@me%3)==0 && @me!=12)  @me=\$a;\r\n                      else  @me=\$b;\r\n                      ",0,421);
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("arcurl","",481,496);
$z[2]=Array("picname","",524,540);
$z[3]=Array("arcurl","",690,705);
$z[4]=Array("title","",723,737);

?>