<?php
$z[0]=Array("global","\r\n                  \$a=\"\r\n                  <li class='col-4-1 last not-animated' data-animate='fadeInUp' >\";\r\n                    \$b=\"\r\n                  \r\n                  <li class='col-4-1 not-animated' data-animate='fadeInUp'>\";\r\n                    if ((@me%4)==0 && @me!=16)  @me=\$a;\r\n                    else  @me=\$b;\r\n                    ",0,405);
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("arcurl","",513,528);
$z[2]=Array("picname","",556,572);
$z[3]=Array("title","",579,593);
$z[4]=Array("arcurl","",699,714);
$z[5]=Array("title","",732,746);

?>