<?php
$z[0]=Array("field","",117,136);
$z[0][4]['name']="title";
$z[1]=Array("global","",137,163);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",204,226);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",266,317);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",2407,2442);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",4293,4322);
$z[5][4]['name']="position";
$z[6]=Array("type","\r\n            <h2>[field:typename /]</h2>\r\n            ",4429,4507);
$z[7]=Array("field","",5051,5070);
$z[7][4]['name']="title";
$z[8]=Array("type"," <a href=\"[field:typelink /]\">[field:typename /]</a> ",5183,5259);
$z[9]=Array("field","",5312,5364);
$z[9][4]['name']="pubdate";
$z[9][4]['function']="MyDate('Y-m-d',@me)";
$z[10]=Array("field","",5574,5592);
$z[10][4]['name']="body";
$z[11]=Array("type","\r\n                      <div class=\"float-right detail-bottom-button\"><a href=\"[field:typeurl/]\">查看更多</a></div>\r\n                      ",5676,5842);
$z[12]=Array("include","",7232,7267);
$z[12][4]['filename']="left.htm";
$z[13]=Array("include","",7375,7412);
$z[13][4]['filename']="footer.htm";

?>