<?php
$z[0]=Array("channel","\r\n                              <li><a href=\"[field:typelink/]\" target=\"_blank\"><span>[field:typename/]</span></a></li>\r\n                              ",1415,1629);
$z[0][4]['typeid']="1";
$z[0][4]['reid']="1";
$z[0][4]['type']="son";
$z[1]=Array("channel","\r\n                              <li><a href=\"[field:typelink/]\" target=\"_blank\"><span>[field:typename/]</span></a></li>\r\n                              ",2803,3017);
$z[1][4]['typeid']="4";
$z[1][4]['reid']="4";
$z[1][4]['type']="son";
$z[2]=Array("channel","\r\n                              <li><a href=\"[field:typelink/]\" target=\"_blank\"><span>[field:typename/]</span></a></li>\r\n                              ",4191,4407);
$z[2][4]['typeid']="11";
$z[2][4]['reid']="11";
$z[2][4]['type']="son";
$z[3]=Array("channel","\r\n                              <li><a href=\"[field:typelink/]\" target=\"_blank\"><span>[field:typename/]</span></a></li>\r\n                              ",5581,5795);
$z[3][4]['typeid']="7";
$z[3][4]['reid']="7";
$z[3][4]['type']="son";
$z[4]=Array("global","",7719,7745);
$z[4][4]['name']="cfg_powerby";
$z[5]=Array("global","",7751,7775);
$z[5][4]['name']="cfg_beian";
$z[6]=Array("global","",7905,7931);
$z[6][4]['name']="cfg_dianhua";

?>