<?php
$z[0]=Array("global","",645,671);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","(@me==\"\")? @me=\" class='current' \":@me=\"\";",937,1029);
$z[1][4]['name']="typeid";
$z[1][4]['runphp']="yes";
$z[2]=Array("channelartlist","\r\n          <li class=\"{dede:field.currentstyle/}\"><a class=\"first-level\" href=\"{dede:field name='typeurl'/}\" target=\"\"><strong >{dede:field name='typename'/}</strong></a><i></i>\r\n            <ul class=\"\">\r\n              {dede:channel type='son' noself='yes'}\r\n              <li class=\"\"><a class=\"\" href=\"[field:typelink/]\" target=\"\"><strong>[field:typename/]</strong></a></li>\r\n              {/dede:channel}\r\n            </ul>\r\n          </li>\r\n          ",1124,1660);
$z[2][4]['typeid']="top";
$z[2][4]['currentstyle']="current";
$z[3]=Array("global","",1977,2003);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("channelartlist","\r\n          <li><a href=\"javascript:;\"><span>{dede:field name='typename'/}</span><i class=\"touch-arrow-down\"></i></a>\r\n            <ul>\r\n              {dede:channel type='son' noself='yes' }\r\n              <li><a href=\"[field:typelink/]\"><span>[field:typename/]</span></a></li>\r\n              {/dede:channel}\r\n            </ul>\r\n          </li>\r\n          ",2734,3154);
$z[4][4]['typeid']="1,4,7,11,0";
$z[5]=Array("channelartlist","\r\n          <li><a href=\"{dede:field name='typeurl'/}\"><span>{dede:field name='typename'/}</span></a></li>\r\n          ",3166,3348);
$z[5][4]['typeid']="16,17,18,0";

?>