<?php
$z[0]=Array("global","",117,143);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",184,213);
$z[1][4]['name']="keywords";
$z[2]=Array("global","",253,283);
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",2373,2408);
$z[3][4]['filename']="head.htm";
$z[4]=Array("field","",4799,4827);
$z[4][4]['name']="content";
$z[5]=Array("include","",9395,9432);
$z[5][4]['filename']="footer.htm";

?>