<?php
$z[0]=Array("global","",117,143);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",184,213);
$z[1][4]['name']="keywords";
$z[2]=Array("global","",253,283);
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",2373,2408);
$z[3][4]['filename']="head.htm";
$z[4]=Array("field","",4259,4288);
$z[4][4]['name']="position";
$z[5]=Array("type","\r\n            <h2>[field:typename /]</h2>\r\n            ",4395,4473);
$z[6]=Array("field","",4917,4945);
$z[6][4]['name']="content";
$z[7]=Array("include","",5127,5162);
$z[7][4]['filename']="left.htm";
$z[8]=Array("include","",5270,5307);
$z[8][4]['filename']="footer.htm";

?>