<?php
$z[0]=Array("field","",117,136);
$z[0][4]['name']="title";
$z[1]=Array("global","",137,163);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",204,233);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",273,331);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",2421,2456);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",4307,4336);
$z[5][4]['name']="position";
$z[6]=Array("type","\r\n            <h2>[field:typename /]</h2>\r\n            ",4443,4521);
$z[7]=Array("list","\r\n                    <li><a href=\"javascript:;\" target=\"\"><img src=\"[field:picname/]\" height=\"74\" data-large-src=\"[field:picname/]\" alt=\"[field:title/]\" /></a></li>\r\n                    ",5111,5321);
$z[8]=Array("include","",5572,5607);
$z[8][4]['filename']="left.htm";
$z[9]=Array("include","",5715,5752);
$z[9][4]['filename']="footer.htm";

?>